version: '3.8'

services:

  fastapi:
    build: ./app
    ports:
      - "8000:8000"  
    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - weaviate
    environment:
      WEAVIATE_URL: http://weaviate:8080

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
